# Generated by Django 2.1.1 on 2018-09-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=500)),
                ('time', models.DateTimeField()),
                ('description', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
            ],
        ),
    ]
