# Generated by Django 2.1.1 on 2018-09-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.TextField(default='10'),
        ),
    ]
