# Generated by Django 2.1.1 on 2018-09-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descritpion',
            new_name='description',
        ),
    ]
